application:
  title: Retrofit Register API

management:
  endpoints:
    web:
      base-path:
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false

swagger:
  api:
    title: National Taxi/PHV Register Data Maintenance (API)
    description: This interface enables integration, via a RESTful API, between LA business processes and systems and the CAZ Service for the purposes of allowing LA’s to maintain details of licensed taxis and Private Hire Vehicles (PHVs) held within the National Taxi/PHV Register – a centralised and authoritative register that details all taxis and PHVs operating in the United Kingdom
    version: 0.1

api:
  max-licences-count: 20000

registerjob:
  db:
    max-errors-count: 100
  lambda:
    name: RetrofitRegisterCsvFromS3Function

spring:
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/caz_vcc
    username: postgres
    password: postgres

springfox:
  documentation:
    swagger:
      v2:
        path: /v1/swagger-docs