### Integration tests configuration

spring:
  datasource:
    url: jdbc:postgresql://${postgres.url:localhost:9999}/caz_vcc
#    url: jdbc:postgresql://${postgres.url:localhost:5432}/caz_vcc
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master-test.yaml

application:
  validation:
    max-errors-count: 10

aws:
  s3:
    endpoint: http://${aws.s3.url:localhost:4572}